//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3SharpUzduotisSuDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karvedys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Karvedys()
        {
            this.Laimejo = new HashSet<Musis>();
        }
    
        public int Id { get; set; }
        public string Vardas { get; set; }
        public string Pavarde { get; set; }
        public string Slapyvardis { get; set; }
        public string Gime { get; set; }
        public string Mire { get; set; }
        public string PulkuSkaicius { get; set; }
        public string Tautybe { get; set; }
    
        public virtual Valstybe Tarnauja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musis> Laimejo { get; set; }
        public virtual MusioDalyvis MusioDalyvis { get; set; }
    }
}
