//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3SharpUzduotisSuDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valstybe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Valstybe()
        {
            this.VykesMusis = new HashSet<Musis>();
            this.Tarnautojas = new HashSet<Karvedys>();
        }
    
        public int Id { get; set; }
        public string Pavadinimas { get; set; }
        public System.DateTime Susikure { get; set; }
        public Nullable<System.DateTime> Zlugo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musis> VykesMusis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karvedys> Tarnautojas { get; set; }
    }
}
